# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5fd93746d47abd20336e6709b6661f8c8e04ec304760ecbe52bc0bbc9719ceae9ef3f4c61299807e5826976c8e59be2ab410dc0263ac3d54c2e01af8c71db903

test:
  secret_key_base: b5564ddf28e46f734d71f7041a7702e93a791c0d1ad21ec9114d5b0a96c93f863bac57aa2cf227cd4cf0d1a135a824f381d5ac2652df3cea4ae16f11a0348873

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
